import "@/styles/globals.css";
import type { Metadata } from "next";
import { Inter, Quicksand, Roboto } from "next/font/google";
import Provider from "./provider";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";
import Community from "@/components/community/Community";

const quicksland = Quicksand({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <Provider>
        <body className={quicksland.className}>
          <Navbar />
          {children}
          <Community />
          <Footer />
        </body>
      </Provider>
    </html>
  );
}
